services:
    DocusignBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']   
        
    DocusignBundle\EnvelopeBuilder:
        arguments: ~
        autowire: false
        shared: false

    League\Flysystem\FilesystemInterface:
        public: true
